const student=
[{
    "id": 1,
    "first_name": "Chloe",
    "last_name": "Bewfield",
    "email": "cbewfield0@technorati.com",
    "gender": "Female",
    "ip_address": "10.97.38.18"
  }, {
    "id": 2,
    "first_name": "Kellen",
    "last_name": "Delion",
    "email": "kdelion1@ucoz.ru",
    "gender": "Male",
    "ip_address": "127.54.56.96"
  }, {
    "id": 3,
    "first_name": "Hewet",
    "last_name": "Giercke",
    "email": "hgiercke2@hibu.com",
    "gender": "Male",
    "ip_address": "1.30.203.39"
  }, {
    "id": 4,
    "first_name": "Cory",
    "last_name": "Upward",
    "email": "cupward3@xing.com",
    "gender": "Female",
    "ip_address": "145.115.155.93"
  }, {
    "id": 5,
    "first_name": "Veriee",
    "last_name": "Dewitt",
    "email": "vdewitt4@utexas.edu",
    "gender": "Female",
    "ip_address": "172.172.77.7"
  }, {
    "id": 6,
    "first_name": "Reeta",
    "last_name": "Mapstone",
    "email": "rmapstone5@statcounter.com",
    "gender": "Genderqueer",
    "ip_address": "72.221.111.196"
  }, {
    "id": 7,
    "first_name": "Chandler",
    "last_name": "Boundey",
    "email": "cboundey6@usda.gov",
    "gender": "Male",
    "ip_address": "109.227.37.200"
  }, {
    "id": 8,
    "first_name": "Leopold",
    "last_name": "Lydster",
    "email": "llydster7@gizmodo.com",
    "gender": "Male",
    "ip_address": "84.53.109.219"
  }, {
    "id": 9,
    "first_name": "Wallace",
    "last_name": "Sharma",
    "email": "wsharma8@boston.com",
    "gender": "Male",
    "ip_address": "242.90.146.139"
  }, {
    "id": 10,
    "first_name": "Trista",
    "last_name": "Paumier",
    "email": "tpaumier9@taobao.com",
    "gender": "Female",
    "ip_address": "112.108.160.4"
  }]
  
module.exports=student; 